### ISSUE TITLE
Override Colors

### ISSUE THREAD

**Issue by ChaosExAnima** [MutualAidNYC/wp-theme#2]
Need to override parent theme colors.

**Comment by jffng** [comment]
Hey @ChaosExAnima !

To confirm, you mean finding all the instances where there are 2020 colors are hardcoded, and overriding them? 

e.g. this button outline style:
<img width="1249" alt="Screen Shot 2020-04-21 at 6 54 10 PM" src="https://user-images.githubusercontent.com/5375500/79922212-86d28a00-8401-11ea-92e0-a68eaa9efb57.png">

**Comment by ChaosExAnima** [comment]
@jffng - Yep, that's exactly it. Ensuring we override the parent theme setting with our own new colors.

**Comment by jffng** [comment]
@ChaosExAnima could this be handled with a filter in the same way you treated the custom logo?

**Comment by ChaosExAnima** [comment]
@jffng how so? From my understanding, the colors are in the parent stylesheet, not provided by PHP.

**Comment by jffng** [comment]
I'm not totally sure, but it looks like TwentyTwenty gives you a way to change the primary color via via the customizer:

<img width="1261" alt="Screen Shot 2020-04-26 at 5 11 06 PM" src="https://user-images.githubusercontent.com/5375500/80319916-1f418380-87e1-11ea-81b2-a016b46fc964.png">

So if we can hook into that, maybe it's a better solution that manually overriding via CSS?

**Comment by ChaosExAnima** [comment]
Hrmmm. I disabled that [here](https://github.com/MutualAidNYC/wp-theme/blob/master/functions.php#L22), but you're right it may be possible to override it. Wanna explore that?
