### ISSUE TITLE
Rename color variables

### ISSUE THREAD

**Issue by ChaosExAnima** [MutualAidNYC/wp-theme#20]
Right now we have `dark`, `dark-alt`, `accent-background`, etc. This is really confusing!

This issue is to rename the colors to be more readable:
* `primary` - Remains the same
* `accent` - Remains the same
* `dark` - `tertiary` (we use it less than `dark-alt`)
* `dark-alt` - `secondary`
* `accent-background` - `light-accent`
* `light-background` - `light-secondary`

**Comment by ChaosExAnima** [comment]
@jffng - Thoughts?

**Comment by jffng** [comment]
> - `primary` - Remains the same
> - `accent` - Remains the same
> - `dark` - `tertiary` (we use it less than dark-alt)
> - `dark-alt` - `secondary`

I think the above makes sense. 

> - accent-background - light-accent

I think avoiding reuse of the word 'accent' is better. From the designs, I only see this color in use as a background color against an H4 and for the separator. Based on that, maybe `--color-highlight` instead?

> - light-background - light-secondary

I also think avoiding reuse of `secondary` is better. In the comps I see it used as a section and accordion header background, so maybe `--color-background` or `--color--background-alt`?  

Probably overthinking it 😅

**Comment by ChaosExAnima** [comment]
> I think avoiding reuse of the word 'accent' is better. From the designs, I only see this color in use as a background color against an H4 and for the separator. Based on that, maybe --color-highlight instead?

Agreed!

> I also think avoiding reuse of secondary is better. In the comps I see it used as a section and accordion header background, so maybe --color-background or --color--background-alt?

I think we should avoid usage of the word "background" as that leads to silly selectors like what I mentioned in #18. Maybe `highlight-alt`?
