### ISSUE TITLE
Beta Design Feedback

### ISSUE THREAD

**Issue by ChaosExAnima** [MutualAidNYC/wp-theme#21]
Some design feedback:
- Change H4s to inline-block so that the background-color doesn’t fill the whole row.
- Change the hover effect on the pill-shaped buttons.
- Add padding between the first paragraph and the hero section.
- On a tags in body copy across the site, underline disappears on hover.
- Links inside of headings should never have an underline.

**Comment by jffng** [comment]
Devon mentioned in slack: 

> there’s a weird interaction between “tech tools” and the other links. If you move your mouse back and forth over the links, you’ll see what I mean. Not sure what’s going on here.

Is this what she's referring to?

![Kapture 2020-04-30 at 13 54 13](https://user-images.githubusercontent.com/5375500/80742886-17882480-8aea-11ea-8c52-d5dbf7f7a476.gif)

**Comment by ChaosExAnima** [comment]
@jffng - That could be it! I wasn't able to replicate anything so wasn't sure what she was talking about. Can you open a new issue and tackle that?
