### ISSUE TITLE
Spike: Airtable Integration 

### ISSUE THREAD

**Issue by ChaosExAnima** [MutualAidNYC/wp-theme#37]
We need to integrate with Airtable to display Resources in a more native fashion:
<img width="633" alt="Screen Shot 2020-05-09 at 6 06 37 PM" src="https://user-images.githubusercontent.com/1760168/81486018-dac1d900-921f-11ea-9dfa-cbbe7fc9afa8.png">

Best way forward seems to be [AirPress](https://github.com/chetmac/airpress), which has a lot of functionality we don't need but also allows queries and iteration with intelligent caching.

Question is how to implement these for use in the theme. Some options:

**Blocks**
Pros:
 - Flexible, many options for styles.
 - Reusable.
 - Preview in editor.

Cons:
 - More code, need JS build pipeline.
 - May need REST endpoints.
 - Setup may be confusing.

**Template**
Pros:
 - Simple, all PHP and CSS.
 - AirPress functions are all PHP already.

Cons:
 - Less flexible and no reuse.
 - No preview functionality.

**Shortcodes**
Pros:
 - Can reuse.
 - Less intuitive, need to know params.
 - All PHP.

Cons:
 - No preview in editor.

**SSR Blocks**
Pros:
 - Same as blocks!
 - Mostly PHP with a tiny bit of JS.

Cons:
 - Slower to render?
 - Need a bit of JS, which if Next needs rendering and such.

**Comment by ChaosExAnima** [comment]
@jffng, open to thoughts here?

**Comment by jffng** [comment]
Blocks seems the heaviest lift, but the most promising over the long term.

> May need REST endpoints.

What do you imagine might be needed here?

Templates could be a useful way to prototype and get something out quickly.

**Comment by ChaosExAnima** [comment]
> What do you imagine might be needed here?

So from my understanding, a "pure" Gutenberg block is one that takes in data and attributes and renders HTML via React, which is saved. If we want to follow this pattern, we'd need to find a way to pull data in via the WP-API from Airtable.

I think a better approach here would be to create a dynamic block that outputs markup via a PHP callback and the `<ServerSideRender>` component. Still, it's a higher lift than a template build and one that can wait till after the MVP.

Anyway, I'm going to make implementation tickets and close this one out!

**Comment by jffng** [comment]
From the WP SSR component docs:

> Server-side rendering in a block’s edit function should be limited to blocks that are heavily dependent on existing PHP rendering logic that is heavily intertwined with data, particularly when there are no endpoints available.

I think this kind of integration qualifies as one of those use cases.

**Comment by ChaosExAnima** [comment]
Created a project with notes to track progress.
