### ISSUE TITLE
Remove large logo from home page

### ISSUE THREAD

**Issue by mollieru** [MutualAidNYC/wp-theme#42]
Per our chat, we'd like to nix the large centered floating logo on the homepage.

**Comment by ChaosExAnima** [comment]
This was done in #40.

**Comment by mollieru** [comment]
@ChaosExAnima I still see it live on the homepage even though that PR is merged :/

**Comment by ChaosExAnima** [comment]
@mollieru - That's because if a PR is merged it doesn't get pushed to production automatically, we need to do it manually. The staging site has everything.
