### ISSUE TITLE
Can't edit styles on Resources page

### ISSUE THREAD

**Issue by mollieru** [MutualAidNYC/wp-theme#46]
not entirely sure what's going on here but I can't get in to edit a bunch of the content from the visual editor on this page
![Screen Shot 2020-05-13 at 7 08 47 PM](https://user-images.githubusercontent.com/3680494/81874978-33a9ae00-954d-11ea-8b01-a92d420945c5.png)

**Comment by ChaosExAnima** [comment]
@mollieru - Yeah, a lot of those blocks are messed up. I'm honestly not sure the best way to tackle this, as it's a strange state it's gotten itself in.

What I'd recommend is waiting on the sidebar to be implemented and redo things, as the current approach is not ideal.

**Comment by mollieru** [comment]
@ChaosExAnima cool thats fine by me! it doesn't look terrible on the front end -- just a little inconsistent w the rest of the site. but also this page will get a new treatment a la the Resource airtable UI redesign so it's all good!

**Comment by ChaosExAnima** [comment]
Resolved by some judicious edits and cleanup. Closing.
