### ISSUE TITLE
Re-order H styles

### ISSUE THREAD

**Issue by mollieru** [MutualAidNYC/wp-theme#48]
Ok so now that we've got the site up, guidance from Rachel on accessibility best practices and a thorough digging around on my part as to how we're actually using text and H stylings in context, I think we need to revise the ordering of our text styles as follows:

**Page title** 
no change

**Page intro text**
The CSS for H2 should be used for a paragraph style intended only for the top of each page. Ideally this is some kind of pre-set block or style, but otherwise, this issue https://github.com/MutualAidNYC/wp-theme/issues/45 will solve this. 

<img width="822" alt="Screen Shot 2020-05-13 at 7 41 42 PM" src="https://user-images.githubusercontent.com/3680494/81876919-ccdac380-9551-11ea-852b-f815677a1945.png">

**h2**
What is currently h4 is what should become our h2. This is the H style we're using as headers of main content areas. One note: the default style should not have the yellow highlight as most of the time we it isn't used that way. 

font-size: 1.75em;
line-height: 1.4;
font-weight: 700;

<img width="443" alt="Screen Shot 2020-05-13 at 7 42 09 PM" src="https://user-images.githubusercontent.com/3680494/81876938-dc5a0c80-9551-11ea-8c75-79a32e999fa3.png">

**h3**
I think we just need to nix this lil guy. we're hardly using it and Rachel says it's throwing off the H ordering for screen readers because we're regularly skipping to H4. 

in that case, what is currently h5 should become h3. 

<img width="601" alt="Screen Shot 2020-05-13 at 7 42 46 PM" src="https://user-images.githubusercontent.com/3680494/81876975-f267cd00-9551-11ea-93f7-f8a63cc2e298.png">

**h4-h6**
keep moving everything else up 2 Hs

**Comment by ChaosExAnima** [comment]
@mollieru - Got it. For the intro text style, would it make sense to do as @jffng suggested and make it part of the Pullquote block?

**Comment by mollieru** [comment]
@ChaosExAnima thats totally fine by me -- though I'm thinking we should run it by Rachel re accessibility + screen readers in case it triggers some other issue we don't know about 🙃

**Comment by ChaosExAnima** [comment]
Did some further thinking, and I think that we should just register a new style for paragraph tags instead, as the accessibility is murky here- this isn't a quote!
