### ISSUE TITLE
Change name of default branch

### ISSUE THREAD

**Issue by HaSistrunk** [MutualAidNYC/wp-theme#97]
I've been following the discussion of moving away from using `master` as the default branch name, and wonder if that makes sense for us. See this article on [Github's support for this](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/). I'm not currently working with this team in MANYC, but thought I would flag for your consideration.

Resource: [Easily rename your git default branch from master to main](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx)

**Comment by ChaosExAnima** [comment]
Thanks for the flag @HaSistrunk! I have seen that but hadn't thought of it for here. Done and done.
